<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<title type="html"><![CDATA[Burgershot - Romanian/Română]]></title>
	<subtitle type="html"><![CDATA[Burgershot - https://www.burgershot.gg]]></subtitle>
	<link rel="self" href="https://www.burgershot.gg/syndication.php"/>
	<id>https://www.burgershot.gg/</id>
	<link rel="alternate" type="text/html" href="https://www.burgershot.gg/"/>
	<updated>2022-07-30T07:14:58Z</updated>
	<generator uri="https://mybb.com">MyBB</generator>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=3333">Cosmin</a>]]></name>
		</author>
		<published>2021-02-27T16:07:30Z</published>
		<updated>2021-02-27T16:08:34Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=1717" />
		<id>https://www.burgershot.gg/showthread.php?tid=1717</id>
		<title xml:space="preserve"><![CDATA[After-School Roleplay]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=1717"><![CDATA[<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: 'Comic Sans MS', cursive;" class="mycode_font">Inceputul </span></span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Ca peste tot , inceputul e greu cand vine vorba de un nou server de samp.Iti pui tot felul de intrebari de genul : E de durata ? Oare se merita ? si multe altele .Nu am sa-ti raspund la aceasta intrebare .Tu decizi ! Nu ai nimic de pierdut .Cert este ca incercam sa lucram cat mai profesionist posibil pentru a va aduce un mod de joc cat mai placut .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Modul de joc este Roleplay Light .Ce inseamna asta ? Inseamna ca jucatorii nu sunt concentrati doar pe roleplay si in general , ei se pot bucura de alte aspecte ale jocului .Asta nu inseamna ca ei au dreptul sa evite anumite situatii unde chiar necesita roleplay cum se cuvine .De asemenea pentru a face parte dintr-o factiune / guvern sau gang sau chiar sa devii leader unuia , esti obligat sa ai cunostinte vaste despre asta pentru ca vei fi supus unor teste , unde concurenta va fi foarte mare .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Economia este una scazuta , unde face jocul cat mai realist .</span>[/font]</span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Acomodarea cu sistemele de business</span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Server-ul nostru dispune de o larga serie de business-uri , precum :</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Magazine publicitare - unde jucatorii pot intra , plasand un anunt prioritar care va fi afisat tuturor jucatorilor online pe server , platind o anumita suma de bani .Important de spus , este ca oricine poate detine un magazin publicitar , iar banii incasati din anunturi se duc in seiful afacerii la care accesul il are doar proprietarul acestuia .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Magazinul general ( sau bine cunoscutul 24/7) - Tastand comanda /buy , ti se va deschide un dialog cu o varietate de produse ce iti vor fi de folos in joc .Bineinteles acestea costa bani , deci asigura-te ca ai suficienti bani in cont .Toti banii incasati de catre un magazin general se vor duce in seiful acestuia , si cum bine stiti doar proprietarul are acces la acesta .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Magazinul de arme - cei mai multi jucatori , iubesc acest timp de afacere .In acest tip de afacere , veti gasi doar armele legale pe server-ul nostru .Cele ilegale le puteti procura de la Dealeri de arme .De asemenea acest tip de afacere poate fi cumparat de orice jucator si cum bine v-am obisnuit toti banii incasati in urma vanzarilor , se duc in seiful afacerii .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Avem si alte tipuri de afaceri , cel mai bine alatura-te si tu comunitatii noastre si descopera chiar TU ! Multe dintre business-uri pot fi folosite ca sediu a gang-urilor ca exemplu : Night Club .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Important: Poti detine cate business-uri doresti .</span>[/font]</span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Acomodarea cu sistemul de case </span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Aici nu sunt prea multe de zis .Fiecare dintre noi isi doreste una pentru diferite motive precum : ai un gang sau iti doresti sa infiintezi unul si nu ai un sediu , ascunderea drogurilor / armelor sau pur si simplu sa ai un loc unde sa dormi .Casele pot fi inchiriate , daca proprietarul este de acord cu asta .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Daca sunteti un dealer de droguri , si casa dumneavoastra a fost desconspirata ca fiind un laborator de droguri , va puteti trezi cu perchezitii , marfa confiscata si arestarea dumneavoastra .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font"> Important : Poti detine cate case doresti </span></span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]    Acomodarea cu factiunile si gang-urile </span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Fiind membru unei factiuni , este cel mai interesant si frumos lucru avand numeroase beneficii precum : arme gratis , skin-uri , nume colorat in TAB , salarii si multe altele .Dar nu uita ca membru sau leader ai si responsabilitati .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Factiunile server-ului nostru sunt :  L.S.P.D , F.B.I , Los Santos Fire &amp; Medical Department , Hitman Agency , Government , San Andreas News .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]LSFMD - membrii acestei factiuni sunt platiti de fiecare data cand duce un pacient la spital , fiindca acesta a ajuns intr-o stare critica .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]LSPD - este cea mai mare factiune patruland pentru linistea orasului .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]FBI - este o organizatie sub acoperire care pot deschide dosare penale .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Government - ca angajat in guvern , esti responsabil pentru a proteja presedintele , respectand sarcinile date de acesta si a te asigura de buna starea cetatenilor .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]San Andreas News - Este factiunea care transmite stiri / anunturi / live-uri pentru a informa cetatenii despre tot ce se intampla in oras .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Hitman Agency - este o factiune bine cunoscuta de jucatori si DAW de asemenea .Ca hitman , tu poti sa omori oameni care sunt sub contract primind jumatate din suma la finalizarea lui .Suma maxima pentru care poti pune contract este de 50.000 &#36; .Pentru a evita abuzurile , liderii acestei factiuni vor fi in mare parte a timpului adminii .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Gang-urile - pot fi create de catre anumiti admini responsabili pe latura aceasta . Cei ce vor sa infiinteze un gang , este nevoit sa aplice pe forum pentru acest lucru ,completand un formular .Va trebui sa asteptati pentru analizarea lui si aprobarea / respingerea lui .Mai multe informatii gasiti in sectiunea corespunzatoare pe forum </span>[/font]</span></span><br />
<br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color">Acomodarea cu factiunea Universitate<br />
</span><br />
<div style="text-align: left;" class="mycode_align"><span style="color: #444444;" class="mycode_color">O noua factiune isi face prezenta pe server-ul nostru si anume Universitatea , unde fiecare jucator ce doreste sa faca parte din politie sau oricare factiune (excluzand gangurile) ca lider sau simplu membru ,va trebui sa ia parte la cursuri si examene .Ce fel de cursuri ?In general ,jucatorii vor invata sa faca roleplay dar si cum sa se comporte ca un membru intr-o factiune .</span></div>
</div>
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Comenzile din chat</span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Aceste comenzi nu sunt greu de retinut , dar e frustrant cand esti incepator .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/me (emotii , trairi ori actiuni)</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/do (exprima o actiune , mai mult o confirmare a /me)</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/b - este folosit pentru OOC (local chat)</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/w - folosit pentru OOC sau IC  sa soptesti unui jucator care e in apropierea ta .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/newb - destinat tuturor jucatorilor in special celor noi care au intrebari referitoare la script .Acest tip de chat este doar pentru Q/A .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/f - este comanda pentru family chat si este folosita in cazuri OOC</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/pr - Personal radio chat .Iti poti cumpara unul din magazinul general si iti poti seta propria frecventa si sa vorbesti cu alti jucatori pe care ii inviti pe canalul tau .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/r - chat pentru departamente .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/d chat pentru toate departamentele</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/sms sau /t pentru a trimite mesaj cuiva </span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]/number - pentru a afla numarul de telefon cuiva / trebuie sa cumperi o carte de telefon si sa detii un telefon </span>[/font]</span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Acomodarea cu sistemul de vehicule</span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Acest sistem de vehicule este unul destul de simplu .Pentru a mentine propria masina in siguranta ai nevoie de o incuietoare .Asta o face mai safe in fata hotilor .Acolo veti gasi doua tipuri de incuietori : Alarm lock - in care masina dumneavoastra va face beep cand cineva incearca sa intre in ea sau Industrial Lock  - tipul acestei incuietori nu va permite hotilor sa o sparga , daca aceasta e incuiata [ /lock ] .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Server-ul dispune de multiple dealership-uri , de la cele mai ietine , la cele mai scumpe .</span>[/font]</span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Acomodarea cu sistemul de drug smuggling / Drug dealer </span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Acest job este unul ilegal si banos , dar trebuie sa fii cu ochii in 4 dupa politisti .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Drug smuggling - la acest job , esti mai mult un caraus , unde esti trimis din punctul A in punctul B pentru a alimenta Crack House .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]Drug Dealer - Poti lua seminte de la drug house , doar daca aceasta are .Daca aceasta nu are seminte , va trebui sa muncesti ca drug smuggling ca sa alimentezi .Acest sistem este la comun .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font="Comic Sans MS", cursive]O data ce ai procurat semintele , poti merge sa le plantezi oriunde .De recomandat este sa le plantati in loc cat mai ferit de ochii lumii pentru ca acestea pot fi furate de alti jucatori .</span>[/font]</span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font=Comic Sans MS, cursive]Acomodarea cu sistemul Double XP </span>[/font]</span></span></div>
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font=Comic Sans MS, cursive]Acest sistem , da oportunitatea jucatorilor ca in timpul lucrului ( job-ului ) sa dobanditi de x2 mai mult skill points la joburi .Acesta se activeaza printr-o simpla modificare in script si nu in joc .De retinut , faptul ca el va fi activat doar la ocazii pe o perioada limitata de timp .</span>[/font]</span></span><br />
<span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font=Comic Sans MS, cursive]Anuntul se va face cu o saptamana inainte .</span>[/font]</span></span><br />
<div style="text-align: center;" class="mycode_align"><span style="color: #444444;" class="mycode_color"><span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font">[font=Comic Sans MS, cursive]Despre Payday</span>[/font]</span></span></div>
<span style="font-size: small;" class="mycode_size"><span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';" class="mycode_font"><span style="color: #444444;" class="mycode_color">[font=Comic Sans MS, cursive]Payday-ul se acorda la fiecare ora fixa xx:00 .Payday-ul se anunta atat in chat cat si pe ecran.Atunci , aveti la dispozitie 5 minute sa tastati comanda /signcheck urmata de un dialog cu cifre random date sa le adaugati  .O data semnat check-ul , primiti payday-ul .Daca cele 5 minute s-au scurs si incercati sa dati /signcheck , aceasta nu va functiona si va trebui sa asteptati pana la urmatorul payday .</span></span>[/font]</span>]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=2347">M.D.</a>]]></name>
		</author>
		<published>2021-01-04T18:26:15Z</published>
		<updated>2021-01-04T18:26:15Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=1494" />
		<id>https://www.burgershot.gg/showthread.php?tid=1494</id>
		<title xml:space="preserve"><![CDATA[Părerea voastră legată de roleplay]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=1494"><![CDATA[Joc SA-MP din 2007 și mă bucură să văd această inițiativă Open MP.<br />
<br />
<span style="font-weight: bold;" class="mycode_b">Cu toate acestea, realistic vorbind, credeți că ar mai exista cerere pentru un server de roleplay?</span> Mă refer la ceea ce majoritatea românilor denumesc „hard roleplay”.<br />
<br />
Am observat că s-a închis recent server-ul RO-RP și că vor trece la o variantă de multiplayer pentru GTA V. Adunând cu ceea ce se mai află în Multi Theft Auto pe server-urile românești de roleplay, ar exista minimum 200-300 de jucători de pe RO-RP și alți 200-300 din MTA (deși acolo majoritatea sunt cu vârste între 10-14 ani și cu greu ar schimba modul de multiplayer). Mai mult, încă mai există mici comunități românești pe server-uri precum LS-RP sau RC-RP.<br />
<br />
Vă cer părerea, deoarece începusem să lucrez la un script luat de la zero, pentru un server de roleplay, și chiar ajunsesem să fac progrese și să adaug funcții pe care le cred foarte interesante pentru fanii RP-ului veritabil:<br />
<br />
• Stocare de date folosind ultima variantă de mySQL cu Salt / SHA256 pentru siguranța parolelor;<br />
• Test de cunoștințe de roleplay esențiale, după înregistrare, folosind dialogs-uri;<br />
• Clase de personaje de început (numite greșit „caractere” în limbaj popular):<br />
   <span style="font-style: italic;" class="mycode_i">* în funcție de ce alegi, pleci cu o anumită sumă de bani și fie o locuință, o mașină sau un job la alegere;</span><br />
• Sistem de hoteluri sau închirieri de camere în regim hotelier:<br />
   <span style="font-style: italic;" class="mycode_i">* mergi la recepție și ți se dă o cameră, dacă nu sunt toate închiriate;</span><br />
• Sistem de investiții în afaceri, prin care în schimbul unei sume de bani investite, ți se returnează între X și Y pe oră;<br />
• Sistem de proprietăți (simple garaje, apartamente, case simple, case cu garaj);<br />
• Sistem de vehicule personale și de serviciu, pentru cele din urmă fiind nevoie de a avea o afacere;<br />
• Sistem de afaceri, care permit proprietarului angajarea altor jucători și urmărirea productivității acestora;<br />
   <span style="font-style: italic;" class="mycode_i">* plus un seif în care se depozitează banii produși de jucători și care poate fi spart;</span><br />
• Sisteme de securitate pentru toate proprietățile, afacerile și vehiculele menționate;<br />
   <span style="font-style: italic;" class="mycode_i">* tot ce ține de securitate se montează interacționând cu alți jucători;</span><br />
• Sistem unic de organizații infracționale (gang-uri sau facțiuni cum li se spune în termeni populari):<br />
   <span style="font-style: italic;" class="mycode_i">* orice jucător cu anumite condiții îndeplinite în joc (ore jucate sau ce mai pot seta eu) poate fonda un astfel de grup;</span><br />
<span style="font-style: italic;" class="mycode_i">   * grupurile au acces la un soi de mini-misiuni prin care au de spart diverse locații sau de jefuit anumite locuri;</span><br />
<span style="font-style: italic;" class="mycode_i">   * în urma acestor mini-misiuni, se pot obține ilegal: mașini, arme și droguri;</span><br />
• Sistem de niveluri pentru abilități precum: trasul cu armele de foc, spargerea vehiculelor, spargerea intrărilor clădirilor;<br />
   <span style="font-style: italic;" class="mycode_i">* toate acestea se învață treptat exersând, iar la spargeri rezultă într-o durată mai scurtă a timpului necesar;</span><br />
<br />
Am cumulat aproape 7.800 de linii de script și mi-ar părea puțin rău de orele de lucru pe care le-am dedicat... Ca să nu mai vorbesc de faptul că am învățat singur să scriptez în Pawno, iar eu n-am nici o treabă cu limbajele de programare.<br />
<br />
<span style="font-weight: bold;" class="mycode_b">De aceea și vreau să aflu părerea voastră — Elaborată, dacă sunteți cunoscători.</span>]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=2662">Doc.</a>]]></name>
		</author>
		<published>2020-10-16T12:37:20Z</published>
		<updated>2020-11-08T16:36:43Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=1248" />
		<id>https://www.burgershot.gg/showthread.php?tid=1248</id>
		<title xml:space="preserve"><![CDATA[Salutare]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=1248"><![CDATA[Salutare, romanasi! Deschid un server de trucking international cu un amic englez si mi-ar prinde bine niste ajutor pe partea de mapping/developing. Forumul vi l dau in pm, daca e cineva interesat sa participe faceti-va cont acolo si imi lasati un PM. Aici nu stiu cat de activ voi fi momentan.]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=1086">BoNNe</a>]]></name>
		</author>
		<published>2019-06-22T18:47:08Z</published>
		<updated>2019-06-22T18:47:08Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=672" />
		<id>https://www.burgershot.gg/showthread.php?tid=672</id>
		<title xml:space="preserve"><![CDATA[*Ce asteptari aveti de la open.mp]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=672"><![CDATA[<div style="text-align: center;" class="mycode_align"><span style="font-style: italic;" class="mycode_i"><span style="font-weight: bold;" class="mycode_b">Personal, ma multumesc cu un player control mai avansat si, de ce nu, NPC-uri (ex: single player).</span></span></div>]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=163">iReal Worlds</a>]]></name>
		</author>
		<published>2019-04-18T10:56:15Z</published>
		<updated>2019-04-18T10:56:15Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=354" />
		<id>https://www.burgershot.gg/showthread.php?tid=354</id>
		<title xml:space="preserve"><![CDATA[Proiecte care asteapta Open.MP]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=354"><![CDATA[Daca ai un proiect si vrei in viitor sa il treci pe Open.MP, scrie aici detalii despre proiect sau ce ar trebui sa aiba OpenMP ca sa treci de la SA:MP aici.]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=191">Reachless</a>]]></name>
		</author>
		<published>2019-04-15T14:45:30Z</published>
		<updated>2019-04-15T14:45:30Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=259" />
		<id>https://www.burgershot.gg/showthread.php?tid=259</id>
		<title xml:space="preserve"><![CDATA["My statement" - Translated/Tradus în Română]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=259"><![CDATA["Cred că este timpul și pentru partea mea de poveste. Aveți cu toții parțial dreptate, dar nu în sensul pe care îl credeți. Nu încerc să separ comunitatea, nu încerc să creez un rival al SA:MP-ului, și un punct foarte important: nu fur codul nimănui. Cu toții credeți că secretul a fost dezvăluit din cauza unui text scris rudimentar căruia îi lipsea tot contextul conversației din care făcea parte. Ați primit o singură parte a poveștii și credeți că totul este stupid, ceea ce este de înțeles având în vedere lipsa de informație completă. Eu am încercat să ofer informații importante fără să intru prea mult în detalii, dar din păcate încercarea mea a avut efecte nedorite, pentru că acum majoritatea dintre voi cunoașteți doar jumătate din povestea din care să trageți concluzii.<br />
<br />
Așa că hai să clarific:<br />
<ul class="mycode_list"><li>Nu încerc să separ comunitatea. Totuși, cineva încearcă să o distrugă - are informații protejate cu grijă, update-uri de mult dorite dar nelansate, amenință că șterge forum-ul (săptămâna trecută), și banează pe oricine este de părere că ceea ce face nu este ok. Această persoană deja a separat comunitatea - lansând două versiuni paralele ale mod-ului, și apoi întrebându-se de ce niciuna nu are succes. Jucătorii au cerut timp de mai mult de un an unirea versiunilor 0.3.7 și 0.3.DL, în timp ce persoana respectivă se îndoia că cinevă ar vrea ca versiunile respective să fie unite. A spus că SA-MP este în decădere, și că va mai avea succes doar 1 an sau 2; și că lui îi convine doar să privească cum acest lucru se întâmplă. Câțiva dintre noi nu suntem de aceeași părere, și am încercat să îl convingem să facă ceva anume - ori să părăsească proiectul, ori să ofere altcuiva oportunitatea de a-l continua. Decăderea comunității probabil că este posibilă, dar SA-MP va dispărea doar dacă nu va mai fi menținut - și asta se întâmplă în acest moment.<br />
</li>
<li>Există un server neoficial de Discord unde, da, oamenii se distrează și fac glume unul pe seama celuilalt. Dar nu a fost creat ca și loc de revoltă. A fost creat pentru că jucătorilor le plăcea SA-MP, și jucătorii folosesc și Discord, așa că, în mod evident, ei le-au combinat. Acesta este un forum neoficial, Kalcor chiar a afirmat în trecut că cei care nu apreciază forum-ul își pot face altul, al lor, oricând își doresc. Iar acum banează persoanele care chiar fac asta. Chiar și așa, nici forum-ul, dar nici server-ul de Discord nu sunt menținute de mine. Ele sunt pur și simplu rezultatele eșecurilor în a evolua. Ceea ce fac eu nu este separare, ci progres.<br />
</li>
<li>Nu incerc să creez un rival al SA-MP-ului. Două din aceste cuvinte sunt greșite: "creez" și "rival". Eu nu "creez" nimic, doar încerc să captez mai multă atenție asupra unui proiect la care deja lucram. Acestea sunt commit-urile din anul trecut: <img src="https://i.imgur.com/JGgR39R.png" loading="lazy"  alt="[Image: JGgR39R.png]" class="mycode_img" /> Nu este nimic nou în asta, deci ce este? Și de ce nu este un rival?<br />
</li>
<li>Da, într-adevăr, am părăsit SA-MP acum 6 ani de zile. Treceți peste.<br />
</li>
</ul>
Nu trădez SA-MP, și nu îl trădez pe Kalcor - el este cel care trădează SA-MP, dar majoritatea oamenilor nu pot concepe acest lucru. Da, a fondat SA-MP, dar asta nu îl face al lui. Sute de alți oameni au lucrat nenumărate ore/zile/săptămâni/ANI ajutând comunitatea, făcând-o ceea ce este acum, dar doar pentru că Kalcor are acces la o mică parte - codul server-ului, el crede că el este pilonul SA-MP și că poate dicta încotro se va duce și când se va opri. La început da, a făcut cea mai mare parte din muncă, dar întrebați-vă cine a ajutat mai mult acest mod în ultimii ani - Kalcor sau oricare dintre oamenii următori?: <img src="https://i.imgur.com/IZYZXhB.png" loading="lazy"  alt="[Image: IZYZXhB.png]" class="mycode_img" /><br />
<br />
Nu încercăm să îl îndepărtăm de la putere, nu vrem să îl facem de rușine pe el sau contribuțiile lui. A fondat acest mod, a adus oameni în proiect, dar toți acei oameni au adus comunitatea unde este acum, și acei oameni - comunitatea, au fost ignorați și alungați. Am încercat să fiu mediatorul, asigurându-mă că părerile lui Kalcor ajung la oameni, și că părerile oamenilor ajung la el, și am fost luat în derâdere de ambele părți. De asemenea, am încercat de nenumărate ori să îl conving pe Kalcor să lase mod-ul în mâinile altcuiva (nu neapărat în mâinile mele, dar eram singurul dispus să fac asta). Care au fost răspunsurile?:<ul class="mycode_list"><li>Nu crede că sunt capabil să fac modificări majore. Evident, nici el nu adaugă modificări majore, și de asemenea crede că nici măcar nu este nevoie de aceste modificări majore, deci ce contează?<br />
</li>
<li>A vrut să îi prezint un plan. Prioritățile mele principale erau fixarea bug-urilor, umplerea golurilor din API, și crearea unei platforme mai bune pentru alte limbaje de programare - de exemplu, un C/plugin API eficient. Nu ar fi fost nici măcar task-uri dificile, ci task-uri pentru care am demonstrat că sunt capabil. Aparent, asta nu este suficient pentru a fi considerat un plan.<br />
</li>
<li>Cuvintele lui exacte au fost: "ei nu merită". Asta este ceea ce crede el despre comunitatea pe care aparent eu încerc să o separ, și despre ideea de a lăsa altă persoană să se ocupe de proiect.<br />
</li>
</ul>
Nimeni nu ar fi deranjat dacă el ar renunța, este ceva perfect normal. Dar ne deranjează faptul că încearcă să tragă în jos orice odată cu el. Aceasta este o comunitate - o comunitate incredibilă cu o mulțime de prietenii de durată, centralizată în jurul unui mod close-source cu un lider paranoic. Încercăm să schimbăm această centralizare, atât. Nu vrem să distrugem SA-MP, nu vrem să separăm comunitatea ("secretul" nostru a fost aflat pentru că încercam să îi introduc în proiect și pe oamenii ignorați care aparțin comunității Rusești, astfel aducând înapoi oamenii deja separați), ci vrem să ne asigurăm că mod-ul va avea continuitate - ceea ce Kalcor nu va face.<br />
<br />
Deci vă prezint:<br />
<br />
<span style="font-size: x-large;" class="mycode_size">open.mp</span><br />
<br />
Acesta este proiectul (și domeniul; forumul burgershot ar fi fost doar un forum temporar până ce am fi creat forum-ul oficial open.mp, lucru care nu s-a întâmplat încă). O echipă de DOUĂZECI ȘI DOI de oameni de top ai San Andreas Multi Player - deținători de servere, scripteri, testeri, și alți lideri de comunități care lucrează împreună pentru a reface totul de la 0. Este ușor să faci un forum; lucrul care a stabilizat controlul lui Kalcor a fost faptul că el a avut tot timpul acces la codul sursă. Există o variantă leaked a SA-MP-ului, dar de la început am spus clar că vom alege drumul cel lung și astfel vom scrie totul de la 0 și vom refuza să folosim cod care nu ar fi al nostru. Așa că am început să facem asta. Inițial am vrut să lansăm o versiune 1.0.0, subit, acela fiind singurul anunț despre open.mp, dar asta nu se mai poate întâmpla.<br />
<br />
Au mai fost astfel de încercări, dar aveau două probleme majore: 1) foloseau cod furat, ceea ce noi nu folosim, și 2) încercau să reinventeze roata, adăugând limbaje noi de scripting, funcții total diferite, etc. Noi facem acest mod compatibil în totalitate cu orice altă versiune existentă a SA-MP-ului. Vei putea face schimbarea către open.mp fără niciun efort, păstrând exact același gamemode, și jucătorii nici măcar nu își vor da seama. Evident, avem în plan să adăugam funcții noi în viitor, dar deocamdată prioritatea noastră este compatibilitatea cu versiunea existentă de SA-MP, stabilitatea, și fixarea bug-urilor (fixuri pe care noi, ca și comunitate, le-am făcut deja pentru că Kalcor a refuzat să le facă).<br />
<br />
Am încercat foarte mult pe parcursul anului trecut să lucrez cu Kalcor la evoluarea SA-MP, doar că am avut și un plan de rezervă. Așa că puteți să rămâneți de partea lui dacă credeți că atitudinea lui se va schimba și va începe subit să facă update-uri (și dacă asta va merge, atunci înseamnă că am reușit să ne îndeplinim obiectivul principal). Sau puteți să ne alăturați nouă, majoritatea comunității, care credem că există o problemă pe care trebuie să o rezolvăm - noi, acei oameni care v-am ajutat, învățat și îndrumat.<br />
<br />
Este alegerea voastră cine credeți că a trădat SA-MP.. Știți deja unde ne găsiți."<br />
<br />
Nu am tradus mot-a-mot, pentru a ma asigura ca poate intelege oricine. Incercati sa imprastiati informatia, spread the word, pentru ca daca veti sustine open.mp, comunitatea nu va disparea.]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
	<entry xmlns="http://www.w3.org/2005/Atom">
		<author>
			<name type="html" xml:space="preserve"><![CDATA[<a href="https://www.burgershot.gg/member.php?action=profile&uid=163">iReal Worlds</a>]]></name>
		</author>
		<published>2019-04-14T14:18:43Z</published>
		<updated>2019-04-14T14:18:43Z</updated>
		<link rel="alternate" type="text/html" href="https://www.burgershot.gg/showthread.php?tid=172" />
		<id>https://www.burgershot.gg/showthread.php?tid=172</id>
		<title xml:space="preserve"><![CDATA[Romanian / Română]]></title>
		<content type="html" xml:space="preserve" xml:base="https://www.burgershot.gg/showthread.php?tid=172"><![CDATA[Dacă au toți ceilalți se poate să nu avem și noi? =))]]></content>
		<draft xmlns="http://purl.org/atom-blog/ns#">false</draft>
	</entry>
</feed>